config/routes.rb
Ernest::Application.routes.draw do
  resources :users
  
 

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/contactus', to: 'static_pages#contactus'
  match '/chooser', to: 'static_pages#chooser'

  

end

app/models/card.rb
class Card < ActiveRecord::Base
  # attr_accessible :title, :body

 
  
attr_accessible :name, :tag_list
  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by_name!(name).cards
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id")
  end
  
  def tag_list
    tags.map(&:name).join(", ")
  end
  
  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :cards, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :card
  # attr_accessible :title, :body
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email


  before_save { |user| user.email = email.downcase }


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home  	
	@user = User.new
end




def contactus
end

def chooser	
	@cards = Card.all
	@users = User.all

end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])



  end

  def update
  @user = User.find(params[:id])
  end


  def new
  	@User = User.new
  end

	def create
    @user = User.new(params[:user])
    if @user.save
    	flash[:success] = "Welcome to the Sample App!"
      redirect_to '/chooser'
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis. 
def full_title(page_title)										# Function Definition
	base_title = "New Way to Find Credit Cards"	# Variable Assignment
	if page_title.empty?												# Boolean Test
		base_title																# Implicit Return
	else
		"#{base_title} | #{page_title}"						# String Interpolation
		end
end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <ul>
      <li><a href="/" alt="About Lot18">Home</a></li>
      <li><a href="/contactus" alt="Contact Lot18">About</a></li>
      <li><a href="/privacy" alt="Privacy Policy">FAQ</a></li>
    </ul>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%=link_to "Home", root_path %></li>
					<li><%=link_to "Contact Us", contactus_path %></li>
					<li><%=link_to "Sign In", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
      <%= yield %>
      <%= render 'layouts/footer' %>
    
</body>


</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/chooser.html.erb
<div class ="move2">

<div class = "show-cards">

	<div class = "containter">

	<h1> LET'S FIND THE PERFECT CARD FOR YOU </h1>
	<h2> HERE ARE 5 SIMPLE QUESTIONS </h2>

<p> 

	<div class="row-fluid">

	<div class="span2">
	test
	</div>	

	<div class = "span10">

<% @cards.each do |card| %>
	<%= card.name %>

<% end %>

	</div>
	</div>



</p>
</div>

</div>

app/views/static_pages/contactus.html.erb
<% provide(:title, 'About') %>

<div class ="move2">

<div class = "show-cards">

	<div class = "container-fluid">



	<h1> ABOUT </h1>

	<div class="row-fluid">

	<div class = "span6">
		<h1><b>An opportunity to learn and inform.</h1> <h2>
	I created this site to help inform and enlighten an often times conflated process
	of individually researching credit card options. </br></br>

	Points. Travel. Cash Back. These are just several of the benefits attached to credit and
	charge cards, and yet no third party sites clearly articulate the prescribed option for you.
	</br></br>
	Instead, you must sort through targeted promos and cluttered sites, rather than pick based on features and benefits
	that make sense to you. This site aims to change that.


	 </h2> 

	</div>
</div>
</div>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>


	<div class = "move2">
	

  <div class = "card-bg" > 



  <h1>NO MORE CONFUSION.<br />  FIND THE RIGHT CARD.</h1><br />





  	  <%= form_for(@user) do |f| %>

   		<%= render 'shared/error_messages' %>


      <%= f.text_field :email, size: 10, placeholder: "ENTER YOUR EMAIL TO TRY IT OUT" %>


      <%= f.submit "PICK THE CARD YOU ACTUALLY WANT", class: "btn-custom" %>
    <% end %>

  	
 
 </div>

  <div class = "login-bg" <p> Already registered? Log in here </p> 


</div>
</div>

app/views/users/new.html.erb
<% provide(:title) %>


<div class = "card-bg" >

  <div class = "email">
    <%= form_for(@user) do |f| %>

   		<%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.text_field :email %>



      <%= f.submit "GIVE ME A SECOND CHANCE", class: "btn-custom" %>
    <% end %>

  </div>
  </div>

app/views/users/show.html.erb
<% provide(@user.email) %>


<div class ="move2">

<div class = "show-cards">

	<h1>  <%= @user.email %></h1>
	<h2> User: <%= @user.id %> </h2>





</div>

</div>

app/views/users/update.html.erb
<% provide(@user.email) %>

<div class ="move2">

<div class = "show-cards">

	<h1> LET'S FIND THE PERFECT CARD FOR YOU </h1>
	<h2> HERE ARE 5 SIMPLE QUESTIONS </h2>

<div class="field">

	<%= form_for(@user) do |f| %>
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>

  <% end %>
</div>


</div>

</div>